nelmio_cors:
    defaults:
        allow_credentials: true
        allow_origin: ['http://localhost:3000'] # Assure-toi que l'URL de ton frontend React est bien spécifiée
        allow_headers: ['Content-Type', 'Authorization', 'X-Requested-With']
        expose_headers: []
        allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
        max_age: 3600
    paths:
        '^/api/': ~
